eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8764
spring:
  application:
    name: service-zuul
zuul:
  routes:
    service-feign:
      path: /service-feign/**
      serviceId: service-feign
    service-one:
      path: /service-one/**
      serviceId: service-one
