spring:
  application:
    name: service-zuul

server:
  port: 8764

eureka:
  client:
    serviceUrl:
    defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    service-feign:
      path: /service-feign/**
      serviceId: service-feign
    service-one:
      path: /service-one/**
      serviceId: service-one
