spring:
  application:
    name: service-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      #手动配置路由
      routes:
        - id: service-one
          uri: lb://SERVICE-ONE
          predicates:
            - Path=/demo/**
          filters:
            - StripPrefix=1

server:
  port: 8765


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/







