spring:
  application:
    name: service-redis

server:
  port: 8788

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

---
spring:
  redis:
    timeout: 60000
    database: 0
    jedis:
      pool:
        max-active: 100
        max-idle: 10
        max-wait: -1
        min-idle: 10
#    host: 127.0.0.1
#    port: 6380
    cluster:
      nodes:
        - 127.0.0.1:6379
        - 127.0.0.1:6380
        - 127.0.0.1:6381
      max-redirects: 3  # 获取失败 最大重定向次数
    sentinel:
      master: master
      nodes:
        - 127.0.0.1:26379
        - 127.0.0.1:26479
        - 127.0.0.1:26579




